Repository Witiko/markdown, pull requests merged in 2022-07, with the labels that each got.

#145 Hotfix #144 by disabling the TeX4ht example
  Makefile
Labels: bug

#146 Revert #145
  Makefile
Labels: bug

#151 Avoid nesting `\markdownIfOption`
  markdown.dtx
Labels: bug, plaintex

#152 Allow syntax extensions to extend `parsers.specialchar`
  markdown.dtx
Labels: bug, lua

#153 Replace calls to xstring with expl3 functions
  markdown.dtx
Labels: latex, technical debt, expl3

#156 Add `luacheck`
  .github/workflows/main.yml
  .luacheckrc
  docstrip.cfg
  markdown.dtx
Labels: lua, technical debt

#157 Replace `keyval` with `l3keys`
  .github/workflows/main.yml
  markdown.dtx
Labels: latex, technical debt, expl3
