Repository Witiko/markdown, pull requests merged in 2023-10, with the labels that each got.

#353 Restore CommonMark testfiles with trailing tabs and spaces
  CHANGES.md
  tests/testfiles/CommonMark_0.30/code_spans/008.test
  tests/testfiles/CommonMark_0.30/code_spans/009.test
  tests/testfiles/CommonMark_0.30/code_spans/010.test
  tests/testfiles/CommonMark_0.30/fenced_code_blocks/011.test
  tests/testfiles/CommonMark_0.30/hard_line_breaks/001.test
  tests/testfiles/CommonMark_0.30/hard_line_breaks/003.test
  tests/testfiles/CommonMark_0.30/hard_line_breaks/004.test
  tests/testfiles/CommonMark_0.30/hard_line_breaks/006.test
  tests/testfiles/CommonMark_0.30/hard_line_breaks/008.test
  tests/testfiles/CommonMark_0.30/hard_line_breaks/010.test
  tests/testfiles/CommonMark_0.30/indented_code_blocks/005.test
  tests/testfiles/CommonMark_0.30/indented_code_blocks/006.test
  tests/testfiles/CommonMark_0.30/indented_code_blocks/012.test
  tests/testfiles/CommonMark_0.30/paragraphs/008.test
Labels: tests

#356 Support attributes on multi-line setext headings
  CHANGES.md
  markdown.dtx
  tests/testfiles/lunamark-markdown/multiline-header-attributes.test
Labels: bug, lua

#354 Auto identifiers extensions
  CHANGES.md
  Makefile
  markdown.dtx
  tests/test.py
  tests/testfiles/lunamark-markdown/auto-identifiers.test
  tests/testfiles/lunamark-markdown/gfm-auto-identifiers.test
Labels: feature request, lua, plaintex, syntax extension, automerge

#360 Fix emphasis in headings
  CHANGES.md
  markdown.dtx
  tests/testfiles/lunamark-markdown/emphasis-in-headings.test
Labels: bug, commonmark, automerge

#361 Add support of bulk redefinition of token renderers and token renderer prototypes in the `\markdownSetup` command using enumeration
  CHANGES.md
  markdown.dtx
Labels: feature request, plaintex, quality of life, expl3

#363 Add support of bulk redefinition of token renderers and token renderer prototypes in the `\markdownSetup` command using enumeration
  CHANGES.md
  markdown.dtx
  tests/support/keyval-setup.tex
  tests/support/setup.tex
  tests/templates/context-mkiv/COMMANDS.m4
Labels: feature request, plaintex, quality of life, expl3

#364 Draft: fix fancy lists with roman numerals
  CHANGES.md
  README.md
  markdown.dtx
  tests/testfiles/lunamark-markdown/fancy-lists.test
Labels: bug, lua
