Repository Witiko/markdown, pull requests merged in 2023-01, with the labels that each got.

#240 Fix ownership of repository before running Docker image
  .github/workflows/main.yml
  CHANGES.md
Labels: bug, docker, continuous integration

#241 In LaTeX, load `paralist` package if option `fancyLists` is enabled
  CHANGES.md
  markdown.dtx
Labels: latex, defaults

#242 Do not fold tabs and spaces into a single space token in unit tests
  CHANGES.md
  Makefile
  README.md
  examples/Makefile
  markdown.dtx
  tests/support/markdownthemewitiko_markdown_test.sty
  tests/support/plain-setup.tex
  tests/templates/latex/COMMANDS.m4
  tests/templates/plain/COMMANDS.m4
  tests/testfiles/lunamark-markdown/html.test
  tests/testfiles/lunamark-markdown/no-slice.test
Labels: bug, automerge, tests

#243 Make `\*group_begin:` and `\*group_end:` the default renderer prototypes for attribute contexts
  CHANGES.md
  markdown.dtx
Labels: plaintex, expl3, automerge, defaults

#244 Use just the first word from `#2` to determine language in `\markdownRendererInputFencedCodePrototype`
  CHANGES.md
  markdown.dtx
Labels: good first issue, latex, context, commonmark, defaults

#247 Map non-breaking space to `writer->nbsp` and U+0000 to U+FFFD in strings
  CHANGES.md
  markdown.dtx
Labels: bug, lua, conversion output, commonmark

#249 Map non-breaking space to `writer->nbsp`
  CHANGES.md
  markdown.dtx
Labels: bug, lua, conversion output, commonmark, automerge

#250 Map U+0000 and U+FFFD to `\markdownRendererReplacementCharacter`
  CHANGES.md
  markdown.dtx
  tests/support/markdownthemewitiko_markdown_test.sty
  tests/support/plain-setup.tex
Labels: bug, lua, plaintex, conversion output, expl3, commonmark

#255 Use fast unit testing in continuous integration
  .github/workflows/main.yml
  CHANGES.md
Labels: good first issue, technical debt, continuous integration

#253 Fix input normalization and move it from Lua CLI and plain TeX layers directly to `convert()` Lua method
  CHANGES.md
  Dockerfile
  Makefile
  markdown.dtx
  tests/testfiles/CommonMark_0.30/fenced-code.test
Labels: bug, lua, automerge

#248 Add support for line blocks
  CHANGES.md
  examples/Makefile
  examples/context-mkii.tex
  examples/context-mkiv.tex
  examples/example.md
  examples/latex.tex
  markdown.dtx
  tests/support/markdownthemewitiko_markdown_test.sty
  tests/support/plain-setup.tex
  tests/testfiles/lunamark-markdown/line-blocks.test
  tests/testfiles/lunamark-markdown/no-line-blocks.test
Labels: feature request, lua, plaintex, syntax extension, automerge
