Repository Witiko/markdown, pull requests merged in 2023-11, with the labels that each got.

#367 Fix miscellaneous issues with the technical documentation
  CHANGES.md
  markdown.dtx
Labels: documentation, automerge

#371 Fix tables in lists
  CHANGES.md
  markdown.dtx
  tests/testfiles/PHP_Markdown/tables.test
Labels: bug, commonmark, automerge

#372 Check that shell access is unrestricted before attempting shell escape
  CHANGES.md
  markdown.dtx
Labels: bug, lt3luabridge

#374 Include developer tools in development Docker image
  .github/workflows/main.yml
  CHANGES.md
  Dockerfile
  Makefile
Labels: docker, quality of life
