Repository Witiko/markdown, pull requests merged in 2024-07, with the labels that each got.

#454 Fix small typos
  CHANGES.md
  README.md
  markdown.dtx
Labels: documentation

#456 Fix brackets in inline notes
  CHANGES.md
  markdown.dtx
  tests/testfiles/regression/github/issue-453.test
  tests/testfiles/unit/lunamark/notes.test
Labels: bug, lua, syntax extension

#463 Add file `DEPENDS.txt`
  CHANGES.md
  Dockerfile
  Makefile
  examples/DEPENDS.txt
  markdown.dtx
  markdown.ins
  tests/DEPENDS.txt
Labels: documentation, automerge

#461 Fix the interplay between lists and citations
  CHANGES.md
  markdown.dtx
  tests/testfiles/regression/github/issue-460.test
Labels: bug, lua, syntax extension, automerge

#472 Produce more meaningful error message when KPathSea has failed to locate a file
  CHANGES.md
  markdown.dtx
Labels: lua, speed, kpathsea
