Repository Witiko/markdown, pull requests merged in 2024-01, with the labels that each got.

#392 Separate default token renderer prototype definitions to a universal theme `witiko/markdown/defaults`
  CHANGES.md
  Dockerfile
  Makefile
  markdown.dtx
  markdown.ins
  tests/support/t-markdownthemewitiko_markdown_test.tex
Labels: plaintex, latex, context, technical debt, expl3, automerge, themes

#394 Add format-independent options `noDefaults` and `plain`, which control the loading of theme `witiko/markdown/defaults`
  CHANGES.md
  markdown.dtx
Labels: plaintex, latex, context, automerge, themes

#396 Do not unnecessarily override math renderer prototypes in LaTeX/ConTeXt
  CHANGES.md
  markdown.dtx
Labels: latex, context, defaults

#400 Add `contentType` Lua option
  CHANGES.md
  markdown.dtx
  tests/testfiles/lunamark-markdown/content-type-block.test
  tests/testfiles/lunamark-markdown/content-type-inline.test
Labels: feature request, lua, quality of life, automerge

#399 Fix handling of spaces in tex backslash extensions
  CHANGES.md
  markdown.dtx
  tests/testfiles/lunamark-markdown/tex-math-double-backslash.test
  tests/testfiles/lunamark-markdown/tex-math-single-backslash.test
Labels: bug, syntax extension, automerge
