Repository Witiko/markdown, pull requests merged in 2024-04, with the labels that each got.

#416 Comply with CommonMark 0.31.2
  CHANGES.md
  markdown.dtx
  tests/testfiles/CommonMark_0.31.2/autolinks/002.test
  tests/testfiles/CommonMark_0.31.2/autolinks/009.test
  tests/testfiles/CommonMark_0.31.2/autolinks/010.test
  tests/testfiles/CommonMark_0.31.2/autolinks/015.test
  tests/testfiles/CommonMark_0.31.2/autolinks/018.test
  tests/testfiles/CommonMark_0.31.2/backslash_escapes/009.test
  tests/testfiles/CommonMark_0.31.2/code_spans/018.test
  tests/testfiles/CommonMark_0.31.2/code_spans/019.test
  tests/testfiles/CommonMark_0.31.2/emphasis_and_strong_emphasis/130.test
  tests/testfiles/CommonMark_0.31.2/emphasis_and_strong_emphasis/131.test
  tests/testfiles/CommonMark_0.31.2/emphasis_and_strong_emphasis/132.test
  tests/testfiles/CommonMark_0.31.2/links/020.test
  tests/testfiles/CommonMark_0.31.2/links/045.test
  tests/testfiles/CommonMark_0.31.2/links/057.test
  tests/testfiles/CommonMark_0.31.2/raw_html/014.test
  tests/testfiles/CommonMark_0.31.2/raw_html/015.test
Labels: commonmark, automerge

#431 Do not end paragraph before `:::` in fenced divs
  CHANGES.md
  markdown.dtx
  tests/testfiles/lunamark-markdown/fenced-divs.test
Labels: bug, lua, syntax extension

#432 Define `parsers.punctuation` in a streaming fashion
  CHANGES.md
  markdown.dtx
Labels: commonmark, automerge, speed

#430 Add default renderers for unnumbered sections in LaTeX
  CHANGES.md
  README.md
  markdown.dtx
Labels: feature request, latex, defaults

#435 Support incremental definitions of token renderers and renderer prototypes in the `\markdownSetup` command
  CHANGES.md
  markdown.dtx
Labels: feature request, plaintex, quality of life, automerge

#438 Make appending operator more efficient and use it in testing framework
  CHANGES.md
  markdown.dtx
  tests/support/keyval-setup.tex
Labels: plaintex, technical debt, expl3, speed

#439 Add `\markinline` plain TeX command
  CHANGES.md
  examples/context-mkiv.tex
  examples/latex-luatex.tex
  examples/latex-pdftex.tex
  markdown.dtx
Labels: feature request, plaintex, latex, quality of life
